apiVersion: apps/v1
kind: Deployment
metadata:
  name: doce-sonho
  labels:
    app: doce-sonho
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: doce-sonho
  template:
    metadata:
      labels:
        app: doce-sonho
    spec:
      containers:
        - name: doce-sonho
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 5000
          resources:
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
