apiVersion: v1
kind: Service
metadata:
  name: doce-sonho-service
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5000
  selector:
    app: doce-sonho
