name: Run Flask API Tests

on:
  push:
    branches:
      - main
    pull_request:
      branches:
        - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Executar Testes
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          touch banco_de_dados.db
          sqlite3 banco_de_dados.db "CREATE TABLE IF NOT EXISTS produtos (id INTEGER PRIMARY KEY AUTOINCREMENT, nome TEXT, descricao TEXT, preco REAL, categoria TEXT, disponivel INTEGER);"
          touch testes/__init__.py
          pytest testes
